services:
  car-service:
    build: ./MyService
    container_name: car-service
    ports:
      - "8080:8080"

  rental-service:
    build: ./RentalService
    container_name: rental-service
    ports:
      - "8081:8081"
    environment:
      CAR_SERVICE_URL: http://car-service:8080
    depends_on:
      - car-service
